"""empty message

Revision ID: 49e05cb5a29f
Revises: 
Create Date: 2021-07-19 16:43:09.140895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49e05cb5a29f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ssn', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=72), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumer')
    # ### end Alembic commands ###
