"""empty message

Revision ID: ec21a5e339db
Revises: 49e05cb5a29f
Create Date: 2021-07-19 17:00:19.993290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec21a5e339db'
down_revision = '49e05cb5a29f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumer_tag_score',
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('consumer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('credit_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumer.uuid'], ),
    sa.ForeignKeyConstraint(['credit_tag_id'], ['credit_tag.id'], ),
    sa.PrimaryKeyConstraint('consumer_id', 'credit_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumer_tag_score')
    op.drop_table('credit_tag')
    # ### end Alembic commands ###
